// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/vdcs.proto

package vdcspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VDCS_ProposeEntry_FullMethodName  = "/vdcs.v1.VDCS/ProposeEntry"
	VDCS_GetLatestRoot_FullMethodName = "/vdcs.v1.VDCS/GetLatestRoot"
	VDCS_GetProof_FullMethodName      = "/vdcs.v1.VDCS/GetProof"
)

// VDCSClient is the client API for VDCS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VDCSClient interface {
	// ProposeEntry submits a new configuration entry.
	ProposeEntry(ctx context.Context, in *ConfigEntry, opts ...grpc.CallOption) (*ProposeResponse, error)
	// GetLatestRoot returns the current Merkle root and version.
	GetLatestRoot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigState, error)
	// GetProof returns a value and inclusion proof for a key.
	GetProof(ctx context.Context, in *GetProofRequest, opts ...grpc.CallOption) (*GetProofResponse, error)
}

type vDCSClient struct {
	cc grpc.ClientConnInterface
}

func NewVDCSClient(cc grpc.ClientConnInterface) VDCSClient {
	return &vDCSClient{cc}
}

func (c *vDCSClient) ProposeEntry(ctx context.Context, in *ConfigEntry, opts ...grpc.CallOption) (*ProposeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposeResponse)
	err := c.cc.Invoke(ctx, VDCS_ProposeEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vDCSClient) GetLatestRoot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigState)
	err := c.cc.Invoke(ctx, VDCS_GetLatestRoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vDCSClient) GetProof(ctx context.Context, in *GetProofRequest, opts ...grpc.CallOption) (*GetProofResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProofResponse)
	err := c.cc.Invoke(ctx, VDCS_GetProof_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VDCSServer is the server API for VDCS service.
// All implementations must embed UnimplementedVDCSServer
// for forward compatibility.
type VDCSServer interface {
	// ProposeEntry submits a new configuration entry.
	ProposeEntry(context.Context, *ConfigEntry) (*ProposeResponse, error)
	// GetLatestRoot returns the current Merkle root and version.
	GetLatestRoot(context.Context, *Empty) (*ConfigState, error)
	// GetProof returns a value and inclusion proof for a key.
	GetProof(context.Context, *GetProofRequest) (*GetProofResponse, error)
	mustEmbedUnimplementedVDCSServer()
}

// UnimplementedVDCSServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVDCSServer struct{}

func (UnimplementedVDCSServer) ProposeEntry(context.Context, *ConfigEntry) (*ProposeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProposeEntry not implemented")
}
func (UnimplementedVDCSServer) GetLatestRoot(context.Context, *Empty) (*ConfigState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestRoot not implemented")
}
func (UnimplementedVDCSServer) GetProof(context.Context, *GetProofRequest) (*GetProofResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProof not implemented")
}
func (UnimplementedVDCSServer) mustEmbedUnimplementedVDCSServer() {}
func (UnimplementedVDCSServer) testEmbeddedByValue()              {}

// UnsafeVDCSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VDCSServer will
// result in compilation errors.
type UnsafeVDCSServer interface {
	mustEmbedUnimplementedVDCSServer()
}

func RegisterVDCSServer(s grpc.ServiceRegistrar, srv VDCSServer) {
	// If the following call panics, it indicates UnimplementedVDCSServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VDCS_ServiceDesc, srv)
}

func _VDCS_ProposeEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VDCSServer).ProposeEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VDCS_ProposeEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VDCSServer).ProposeEntry(ctx, req.(*ConfigEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _VDCS_GetLatestRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VDCSServer).GetLatestRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VDCS_GetLatestRoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VDCSServer).GetLatestRoot(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VDCS_GetProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VDCSServer).GetProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VDCS_GetProof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VDCSServer).GetProof(ctx, req.(*GetProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VDCS_ServiceDesc is the grpc.ServiceDesc for VDCS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VDCS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vdcs.v1.VDCS",
	HandlerType: (*VDCSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProposeEntry",
			Handler:    _VDCS_ProposeEntry_Handler,
		},
		{
			MethodName: "GetLatestRoot",
			Handler:    _VDCS_GetLatestRoot_Handler,
		},
		{
			MethodName: "GetProof",
			Handler:    _VDCS_GetProof_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/vdcs.proto",
}
