// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/vdcs.proto

package vdcspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Operation defines the type of mutation.
type Operation int32

const (
	Operation_OPERATION_UNSPECIFIED Operation = 0
	Operation_OPERATION_SET         Operation = 1
	Operation_OPERATION_DELETE      Operation = 2
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_SET",
		2: "OPERATION_DELETE",
	}
	Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"OPERATION_SET":         1,
		"OPERATION_DELETE":      2,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_vdcs_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_proto_vdcs_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_proto_vdcs_proto_rawDescGZIP(), []int{0}
}

// ConfigEntry is an immutable record of a configuration change.
// This is the fundamental unit of the append-only log.
type ConfigEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index is the monotonic sequence number of the entry in the log.
	Index uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// Timestamp is the Unix nanos when the entry was created.
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// AuthorID is the identifier of the entity making the change (e.g., public key or user ID).
	AuthorId string `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	// Key is the configuration key being modified.
	Key string `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	// ValueHash is the SHA-256 hash of the value.
	// We store the hash in the log entry to keep the log lightweight and
	// to allow separate heavy value storage if needed (though v1 may inline values).
	// For v1, we might want to include the Value itself if small, but the spec says "ValueHash".
	// Let's stick to the spec strictly: "ValueHash".
	// Note: If we only store ValueHash, we need a way to transport the actual Value.
	// The spec's "Materialized State" implies we have the values.
	// Let's add `bytes value` as an optional field for transport, but the signature
	// should arguably cover the semantic content.
	// The User Spec said: "ValueHash [32]byte".
	// We will adhere to that for the signed envelope.
	ValueHash []byte `protobuf:"bytes,5,opt,name=value_hash,json=valueHash,proto3" json:"value_hash,omitempty"`
	// Operation is the type of change (SET or DELETE).
	Operation Operation `protobuf:"varint,6,opt,name=operation,proto3,enum=vdcs.v1.Operation" json:"operation,omitempty"`
	// PrevHash is the SHA-256 hash of the previous log entry.
	// This creates the hash chain.
	PrevHash []byte `protobuf:"bytes,7,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	// EntryHash is the SHA-256 hash of this entry (excluding Signature?).
	// Usually this is computed, not stored, or stored for convenience.
	// The signature covers this hash.
	EntryHash []byte `protobuf:"bytes,8,opt,name=entry_hash,json=entryHash,proto3" json:"entry_hash,omitempty"`
	// Signature is the Ed25519 signature of EntryHash by AuthorID.
	Signature []byte `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
	// ... (previous fields)
	Value         []byte `protobuf:"bytes,10,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigEntry) Reset() {
	*x = ConfigEntry{}
	mi := &file_proto_vdcs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigEntry) ProtoMessage() {}

func (x *ConfigEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vdcs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigEntry.ProtoReflect.Descriptor instead.
func (*ConfigEntry) Descriptor() ([]byte, []int) {
	return file_proto_vdcs_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigEntry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ConfigEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ConfigEntry) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *ConfigEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigEntry) GetValueHash() []byte {
	if x != nil {
		return x.ValueHash
	}
	return nil
}

func (x *ConfigEntry) GetOperation() Operation {
	if x != nil {
		return x.Operation
	}
	return Operation_OPERATION_UNSPECIFIED
}

func (x *ConfigEntry) GetPrevHash() []byte {
	if x != nil {
		return x.PrevHash
	}
	return nil
}

func (x *ConfigEntry) GetEntryHash() []byte {
	if x != nil {
		return x.EntryHash
	}
	return nil
}

func (x *ConfigEntry) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ConfigEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ConfigState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	StateRoot     []byte                 `protobuf:"bytes,2,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	LastEntryHash []byte                 `protobuf:"bytes,3,opt,name=last_entry_hash,json=lastEntryHash,proto3" json:"last_entry_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigState) Reset() {
	*x = ConfigState{}
	mi := &file_proto_vdcs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigState) ProtoMessage() {}

func (x *ConfigState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vdcs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigState.ProtoReflect.Descriptor instead.
func (*ConfigState) Descriptor() ([]byte, []int) {
	return file_proto_vdcs_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigState) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigState) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *ConfigState) GetLastEntryHash() []byte {
	if x != nil {
		return x.LastEntryHash
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_vdcs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vdcs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_vdcs_proto_rawDescGZIP(), []int{2}
}

type ProposeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeResponse) Reset() {
	*x = ProposeResponse{}
	mi := &file_proto_vdcs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeResponse) ProtoMessage() {}

func (x *ProposeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vdcs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeResponse.ProtoReflect.Descriptor instead.
func (*ProposeResponse) Descriptor() ([]byte, []int) {
	return file_proto_vdcs_proto_rawDescGZIP(), []int{3}
}

type GetProofRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProofRequest) Reset() {
	*x = GetProofRequest{}
	mi := &file_proto_vdcs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProofRequest) ProtoMessage() {}

func (x *GetProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vdcs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProofRequest.ProtoReflect.Descriptor instead.
func (*GetProofRequest) Descriptor() ([]byte, []int) {
	return file_proto_vdcs_proto_rawDescGZIP(), []int{4}
}

func (x *GetProofRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetProofResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ValueHash     []byte                 `protobuf:"bytes,2,opt,name=value_hash,json=valueHash,proto3" json:"value_hash,omitempty"`
	Siblings      [][]byte               `protobuf:"bytes,3,rep,name=siblings,proto3" json:"siblings,omitempty"`
	IsLeft        []bool                 `protobuf:"varint,4,rep,packed,name=is_left,json=isLeft,proto3" json:"is_left,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProofResponse) Reset() {
	*x = GetProofResponse{}
	mi := &file_proto_vdcs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProofResponse) ProtoMessage() {}

func (x *GetProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vdcs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProofResponse.ProtoReflect.Descriptor instead.
func (*GetProofResponse) Descriptor() ([]byte, []int) {
	return file_proto_vdcs_proto_rawDescGZIP(), []int{5}
}

func (x *GetProofResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetProofResponse) GetValueHash() []byte {
	if x != nil {
		return x.ValueHash
	}
	return nil
}

func (x *GetProofResponse) GetSiblings() [][]byte {
	if x != nil {
		return x.Siblings
	}
	return nil
}

func (x *GetProofResponse) GetIsLeft() []bool {
	if x != nil {
		return x.IsLeft
	}
	return nil
}

var File_proto_vdcs_proto protoreflect.FileDescriptor

const file_proto_vdcs_proto_rawDesc = "" +
	"\n" +
	"\x10proto/vdcs.proto\x12\avdcs.v1\"\xb1\x02\n" +
	"\vConfigEntry\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"value_hash\x18\x05 \x01(\fR\tvalueHash\x120\n" +
	"\toperation\x18\x06 \x01(\x0e2\x12.vdcs.v1.OperationR\toperation\x12\x1b\n" +
	"\tprev_hash\x18\a \x01(\fR\bprevHash\x12\x1d\n" +
	"\n" +
	"entry_hash\x18\b \x01(\fR\tentryHash\x12\x1c\n" +
	"\tsignature\x18\t \x01(\fR\tsignature\x12\x14\n" +
	"\x05value\x18\n" +
	" \x01(\fR\x05value\"n\n" +
	"\vConfigState\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x1d\n" +
	"\n" +
	"state_root\x18\x02 \x01(\fR\tstateRoot\x12&\n" +
	"\x0flast_entry_hash\x18\x03 \x01(\fR\rlastEntryHash\"\a\n" +
	"\x05Empty\"\x11\n" +
	"\x0fProposeResponse\"#\n" +
	"\x0fGetProofRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"x\n" +
	"\x10GetProofResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"value_hash\x18\x02 \x01(\fR\tvalueHash\x12\x1a\n" +
	"\bsiblings\x18\x03 \x03(\fR\bsiblings\x12\x17\n" +
	"\ais_left\x18\x04 \x03(\bR\x06isLeft*O\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rOPERATION_SET\x10\x01\x12\x14\n" +
	"\x10OPERATION_DELETE\x10\x022\xbe\x01\n" +
	"\x04VDCS\x12>\n" +
	"\fProposeEntry\x12\x14.vdcs.v1.ConfigEntry\x1a\x18.vdcs.v1.ProposeResponse\x125\n" +
	"\rGetLatestRoot\x12\x0e.vdcs.v1.Empty\x1a\x14.vdcs.v1.ConfigState\x12?\n" +
	"\bGetProof\x12\x18.vdcs.v1.GetProofRequest\x1a\x19.vdcs.v1.GetProofResponseB%Z#github.com/rrb115/vdcs/proto;vdcspbb\x06proto3"

var (
	file_proto_vdcs_proto_rawDescOnce sync.Once
	file_proto_vdcs_proto_rawDescData []byte
)

func file_proto_vdcs_proto_rawDescGZIP() []byte {
	file_proto_vdcs_proto_rawDescOnce.Do(func() {
		file_proto_vdcs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_vdcs_proto_rawDesc), len(file_proto_vdcs_proto_rawDesc)))
	})
	return file_proto_vdcs_proto_rawDescData
}

var file_proto_vdcs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_vdcs_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_vdcs_proto_goTypes = []any{
	(Operation)(0),           // 0: vdcs.v1.Operation
	(*ConfigEntry)(nil),      // 1: vdcs.v1.ConfigEntry
	(*ConfigState)(nil),      // 2: vdcs.v1.ConfigState
	(*Empty)(nil),            // 3: vdcs.v1.Empty
	(*ProposeResponse)(nil),  // 4: vdcs.v1.ProposeResponse
	(*GetProofRequest)(nil),  // 5: vdcs.v1.GetProofRequest
	(*GetProofResponse)(nil), // 6: vdcs.v1.GetProofResponse
}
var file_proto_vdcs_proto_depIdxs = []int32{
	0, // 0: vdcs.v1.ConfigEntry.operation:type_name -> vdcs.v1.Operation
	1, // 1: vdcs.v1.VDCS.ProposeEntry:input_type -> vdcs.v1.ConfigEntry
	3, // 2: vdcs.v1.VDCS.GetLatestRoot:input_type -> vdcs.v1.Empty
	5, // 3: vdcs.v1.VDCS.GetProof:input_type -> vdcs.v1.GetProofRequest
	4, // 4: vdcs.v1.VDCS.ProposeEntry:output_type -> vdcs.v1.ProposeResponse
	2, // 5: vdcs.v1.VDCS.GetLatestRoot:output_type -> vdcs.v1.ConfigState
	6, // 6: vdcs.v1.VDCS.GetProof:output_type -> vdcs.v1.GetProofResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_vdcs_proto_init() }
func file_proto_vdcs_proto_init() {
	if File_proto_vdcs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_vdcs_proto_rawDesc), len(file_proto_vdcs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vdcs_proto_goTypes,
		DependencyIndexes: file_proto_vdcs_proto_depIdxs,
		EnumInfos:         file_proto_vdcs_proto_enumTypes,
		MessageInfos:      file_proto_vdcs_proto_msgTypes,
	}.Build()
	File_proto_vdcs_proto = out.File
	file_proto_vdcs_proto_goTypes = nil
	file_proto_vdcs_proto_depIdxs = nil
}
